# Generated by Django 3.0.5 on 2020-10-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0006_auto_20201009_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='a11',
            new_name='A11',
        ),
    ]
