# Generated by Django 3.0.5 on 2020-10-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0007_auto_20201009_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seatNumber', models.CharField(max_length=500)),
                ('totalSeat', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('bookingDate', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex.Customer')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplex.Movie')),
            ],
        ),
    ]
