# Generated by Django 3.0.5 on 2020-10-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0008_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='watchers',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
