# Generated by Django 3.0.5 on 2020-10-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0012_tempmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmovie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='temp_movie_pic/movie_poster/'),
        ),
    ]
