# Generated by Django 3.0.5 on 2020-10-13 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0013_auto_20201011_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmovie',
            name='theatre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplex.Theatre'),
        ),
        migrations.AlterField(
            model_name='tempmovie',
            name='distributor_status',
            field=models.CharField(choices=[('Request Not Made', 'Request Not Made'), ('Sold To Theatre', 'Sold To Theatre'), ('Request Made', 'Request Made'), ('Request Declined', 'Request Declined')], default='Request Not Made', max_length=50),
        ),
        migrations.AlterField(
            model_name='tempmovie',
            name='producer_status',
            field=models.CharField(choices=[('Request Not Made', 'Request Not Made'), ('Sold To Distributor', 'Sold To Distributor'), ('Request Made', 'Request Made'), ('Request Declined', 'Request Declined')], default='Request Not Made', max_length=80),
        ),
    ]
