# Generated by Django 3.0.5 on 2020-10-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0014_auto_20201013_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmovie',
            name='theatre_status',
            field=models.CharField(choices=[('Movie Released', 'Movie Released'), ('Movie Not Released', 'Movie Not Released')], default='Movie Not Released', max_length=80),
        ),
    ]
