# Generated by Django 3.0.5 on 2020-10-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0016_movie_theatre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
