# Generated by Django 3.0.5 on 2021-03-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0018_auto_20210313_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/user.jpg', null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
